# typed: false
# frozen_string_literal: true

# Generated by scripts/gen-formula.sh — do not edit by hand.
# Every tagged release regenerates this file with fresh checksums.
class Dok < Formula
  desc "Docker output, made readable - what eza is to ls"
  homepage "https://github.com/alsaadii98/cool-docker-commands"
  version "0.1.2"
  license "MIT"
  head "https://github.com/alsaadii98/cool-docker-commands.git", branch: "main"

  on_macos do
    on_arm do
      url "https://github.com/alsaadii98/cool-docker-commands/releases/download/v0.1.2/dok-0.1.2-aarch64-apple-darwin.tar.gz"
      sha256 "29603eada2a797a0088ce44a0be0dbd77b9f87d9efd1a7749aded4ad84a7bfcf"
    end
    on_intel do
      url "https://github.com/alsaadii98/cool-docker-commands/releases/download/v0.1.2/dok-0.1.2-x86_64-apple-darwin.tar.gz"
      sha256 "e6d82cea139f9438540c4ebaee8018b979e29e05981a9272f3d34bb1b0d09efd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alsaadii98/cool-docker-commands/releases/download/v0.1.2/dok-0.1.2-aarch64-unknown-linux-musl.tar.gz"
      sha256 "a2a1df4a1399ef42b1eba045c0aad2a5ea707c80b8318d4b13fb11638d775be9"
    end
    on_intel do
      url "https://github.com/alsaadii98/cool-docker-commands/releases/download/v0.1.2/dok-0.1.2-x86_64-unknown-linux-musl.tar.gz"
      sha256 "bf55fb5acef156302de1372effd15616fe2b05ac4d4c103e6a023abafd001534"
    end
  end

  # `brew install --HEAD` builds from source and needs a toolchain; the
  # normal path installs the prebuilt binary and needs nothing at all.
  head do
    depends_on "rust" => :build
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      # Archives contain a single dok-<version>-<target>/ directory.
      root = Dir["dok-*"].find { |d| File.directory?(d) } || "."
      bin.install "#{root}/dok"
      doc.install "#{root}/README.md", "#{root}/CHANGELOG.md" if File.exist?("#{root}/README.md")
    end
  end

  test do
    assert_match "dok", shell_output("#{bin}/dok --version")

    # --demo renders a canned stack, so this works on a machine with no
    # Docker daemon (which is exactly what brew test runs on).
    output = shell_output("#{bin}/dok ps --demo --color=never --icons=none")
    assert_match "demo-shop", output

    # Without a daemon and without --demo it must fail loudly, not hang.
    output = shell_output("DOCKER_HOST=unix:///nonexistent #{bin}/dok ps 2>&1", 1)
    assert_match(/docker/i, output)
  end
end
