# typed: false
# frozen_string_literal: true

# Generated by scripts/gen-formula.sh — do not edit by hand.
# Every tagged release regenerates this file with fresh checksums.
class Dok < Formula
  desc "Docker output, made readable - what eza is to ls"
  homepage "https://github.com/alsaadii98/dok"
  version "0.2.1"
  license "MIT"
  head "https://github.com/alsaadii98/dok.git", branch: "main"

  on_macos do
    on_arm do
      url "https://github.com/alsaadii98/dok/releases/download/v0.2.1/dok-0.2.1-aarch64-apple-darwin.tar.gz"
      sha256 "5441401e6e7fe8221d845d395a6f3b1aa0b10e22b3fb9f0e6c20b1b650232614"
    end
    on_intel do
      url "https://github.com/alsaadii98/dok/releases/download/v0.2.1/dok-0.2.1-x86_64-apple-darwin.tar.gz"
      sha256 "66bb9570ccba3403ce44f131345d4d73aba9969c4d03d86f5e99d65ffe7e3f1b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alsaadii98/dok/releases/download/v0.2.1/dok-0.2.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "2ace37a16f5296d208407779dbbb2aa8f776a3fd1573a078189e514892f28c2f"
    end
    on_intel do
      url "https://github.com/alsaadii98/dok/releases/download/v0.2.1/dok-0.2.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "9a6633197d257be79f9f8c2598507c5279dc65a9e21d37388717ddefd1164efb"
    end
  end

  # `brew install --HEAD` builds from source and needs a toolchain; the
  # normal path installs the prebuilt binary and needs nothing at all.
  head do
    depends_on "rust" => :build
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      # Archives contain a single dok-<version>-<target>/ directory.
      root = Dir["dok-*"].find { |d| File.directory?(d) } || "."
      bin.install "#{root}/dok"
      doc.install "#{root}/README.md", "#{root}/CHANGELOG.md" if File.exist?("#{root}/README.md")
      generate_completions_from_executable(bin/"dok", "completions")
    end
  end

  test do
    assert_match "dok", shell_output("#{bin}/dok --version")

    # --demo renders a canned stack, so this works on a machine with no
    # Docker daemon (which is exactly what brew test runs on).
    output = shell_output("#{bin}/dok ps --demo --color=never --icons=none")
    assert_match "demo-shop", output

    # Without a daemon and without --demo it must fail loudly, not hang.
    output = shell_output("DOCKER_HOST=unix:///nonexistent #{bin}/dok ps 2>&1", 1)
    assert_match(/docker/i, output)
  end
end
