# typed: false
# frozen_string_literal: true

# Generated by scripts/gen-formula.sh — do not edit by hand.
# Every tagged release regenerates this file with fresh checksums.
class Dok < Formula
  desc "Docker output, made readable - what eza is to ls"
  homepage "https://github.com/alsaadii98/cool-docker-commands"
  version "0.1.4"
  license "MIT"
  head "https://github.com/alsaadii98/cool-docker-commands.git", branch: "main"

  on_macos do
    on_arm do
      url "https://github.com/alsaadii98/cool-docker-commands/releases/download/v0.1.4/dok-0.1.4-aarch64-apple-darwin.tar.gz"
      sha256 "7d6e182442438723f01f8cc3ad3b3457fb4fc667ef968497dd73643bf47329b4"
    end
    on_intel do
      url "https://github.com/alsaadii98/cool-docker-commands/releases/download/v0.1.4/dok-0.1.4-x86_64-apple-darwin.tar.gz"
      sha256 "d8f06f066b75d51bf55a6fb8bd79bbebbdecddae3ac55726791153b49fc0ff14"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alsaadii98/cool-docker-commands/releases/download/v0.1.4/dok-0.1.4-aarch64-unknown-linux-musl.tar.gz"
      sha256 "84e9f656515b43d0918a7466f57c8f335400d9f3a572f02a63cfdc7bdf6df12e"
    end
    on_intel do
      url "https://github.com/alsaadii98/cool-docker-commands/releases/download/v0.1.4/dok-0.1.4-x86_64-unknown-linux-musl.tar.gz"
      sha256 "69a3de3157bd4d7fec36f5eb077feb19f22986470e302721124f71bb99d5c829"
    end
  end

  # `brew install --HEAD` builds from source and needs a toolchain; the
  # normal path installs the prebuilt binary and needs nothing at all.
  head do
    depends_on "rust" => :build
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      # Archives contain a single dok-<version>-<target>/ directory.
      root = Dir["dok-*"].find { |d| File.directory?(d) } || "."
      bin.install "#{root}/dok"
      doc.install "#{root}/README.md", "#{root}/CHANGELOG.md" if File.exist?("#{root}/README.md")
    end
  end

  test do
    assert_match "dok", shell_output("#{bin}/dok --version")

    # --demo renders a canned stack, so this works on a machine with no
    # Docker daemon (which is exactly what brew test runs on).
    output = shell_output("#{bin}/dok ps --demo --color=never --icons=none")
    assert_match "demo-shop", output

    # Without a daemon and without --demo it must fail loudly, not hang.
    output = shell_output("DOCKER_HOST=unix:///nonexistent #{bin}/dok ps 2>&1", 1)
    assert_match(/docker/i, output)
  end
end
